slasqrr/user/models.py
# -*- coding: utf-8 -*-
import datetime as dt

from flask.ext.login import UserMixin

from slasqrr.extensions import bcrypt
from slasqrr.database import (
    Column,
    db,
    Model,
    ReferenceCol,
    relationship,
    SurrogatePK,
)


class Role(SurrogatePK, Model):
    __tablename__ = 'roles'
    name = Column(db.String(80), unique=True, nullable=False)
    user_id = ReferenceCol('users', nullable=True)
    user = relationship('User', backref='roles')

    def __init__(self, name, **kwargs):
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        return '<Role({name})>'.format(name=self.name)


class User(UserMixin, SurrogatePK, Model):
    __tablename__ = 'users'
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(80), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.String(128), nullable=True)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)

    def __init__(self, username, email, password=None, **kwargs):
        db.Model.__init__(self, username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        return bcrypt.check_password_hash(self.password, value)

    @property
    def full_name(self):
        return "{0} {1}".format(self.first_name, self.last_name)

    def __repr__(self):
        return '<User({username!r})>'.format(username=self.username)


class Post(SurrogatePK, Model):

    __tablename__ = 'post'

    created = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    alias = Column(db.String(50), nullable=True)
    text = Column(db.Text, nullable=True)
    picture = Column(db.String(100), nullable=True)

slasqrr/user/forms.py
from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from .models import User

class RegisterForm(Form):
    username = TextField('Username',
                    validators=[DataRequired(), Length(min=3, max=25)])
    email = TextField('Email',
                    validators=[DataRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password',
                                validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                [DataRequired(), EqualTo('password', message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append("Username already registered")
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        return True

slasqrr/app.py
# -*- coding: utf-8 -*-
'''The app module, containing the app factory function.'''
from flask import Flask, render_template
from flask.ext.uploads import configure_uploads, patch_request_class

from slasqrr.settings import ProdConfig
from slasqrr.assets import assets
from slasqrr.extensions import (
    bcrypt,
    cache,
    db,
    login_manager,
    migrate,
    debug_toolbar,
    photos)
from slasqrr import public, user, rpi


def create_app(config_object=ProdConfig):
    '''An application factory, as explained here:
        http://flask.pocoo.org/docs/patterns/appfactories/

    :param config_object: The configuration object to use.
    '''
    app = Flask(__name__)
    app.config.from_object(config_object)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app


def register_extensions(app):
    assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    configure_uploads(app, photos)
    patch_request_class(app, 10 * 1024 * 1024)  # 10MB max upload size
    return None


def register_blueprints(app):
    app.register_blueprint(public.views.blueprint)
    app.register_blueprint(user.views.blueprint)
    app.register_blueprint(rpi.views.blueprint)
    return None


def register_errorhandlers(app):
    def render_error(error):
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template("{0}.html".format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None

slasqrr/rpi/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from . import views

slasqrr/rpi/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, jsonify, current_app
from slasqrr.extensions import photos

from slasqrr.user.models import Post


blueprint = Blueprint('rpi', __name__, static_folder='../static', url_prefix='/pi')


@blueprint.route('/', methods=['GET'])
def rpi_client():
    is_prod = current_app.config['ENV'] == 'prod'
    return render_template('rpi/view.html', prod=is_prod)


@blueprint.route('/<post_id>', methods=['GET'])
def posts(post_id):
    if post_id > 0:
        data = Post.query.filter(Post.id > post_id).limit(15).all()
    else:
        data = Post.query.limit(15).all()

    posts = []
    for post in data:
        url = photos.url(post.picture) if post.picture is not None else ''
        posts.append({'id': post.id, 'message': post.text, 'picture': url, 'alias': post.alias})

    return jsonify(posts=posts)

slasqrr/user/__init__.py
'''The user module.'''

from . import views

slasqrr/user/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template
from flask.ext.login import login_required

blueprint = Blueprint("user", __name__, url_prefix='/users',
                        static_folder="../static")


@blueprint.route("/")
@login_required
def members():
    return render_template("users/members.html")

slasqrr/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

slasqrr/templates/footer.html
<footer>
    <small>
        <ul class="company">
            <li>© <span class="rocky">STABEN</span></li>
        </ul>

        <ul class="footer-nav">

            <li><a href="{{ url_for('public.about') }}">Om</a></li>

        </ul>
    </small>
</footer>

slasqrr/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}
  
    SLASQRR
  
    {% endblock %}
  </title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <meta property="og:url" content="http://slasquen.rocks" />
  <meta property="og:title" content="Dödsfest är bra fest." />
  <meta property="og:site_name" content="Slasquen.rocks"/>
  <meta property="og:description" content="STABENs finfina eventsida för Slasquen. Kom igen det blir kul!"/>
  <meta property="og:image" content="http://slasquen.rocks/static/img/gruppbild.jpg" />


  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  <link rel="stylesheet" href="{{ url_for('static', filename='libs/font-awesome4/css/font-awesome.min.css') }}">
  {% assets "css_all" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}

  {% block css %}{% endblock %}

</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
{% with form=form  %}
{% include "nav.html" %}
{% endwith %}

<header>{% block header %}{% endblock %}</header>
<div class="{% block content_class %}container{% endblock content_class %}">

  <div role="main">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{message}}
        </div><!-- end .alert -->
        {% endfor %}
      </div><!-- end col-md -->
    </div><!-- end row -->
        {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
  </div>

</div><!-- end container -->

{% include "footer.html" %}

<!-- JavaScript at the bottom for fast page loading -->
{% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% block js %}{% endblock %}
    {% if prod %}
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-62568300-1', 'auto');
            ga('send', 'pageview');
        </script>
    {% endif %}
<!-- end scripts -->
{% endblock %}
</body>
</html>

slasqrr/templates/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">

        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand rocky" href="{{ url_for('public.home') }}">
                <!-- Don't remove the span! Used with CSS. -->
                <span>SLASQRR</span>
            </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('public.home') }}">Hem</a></li>
                <li><a href="{{ url_for('rpi.rpi_client') }}">Stream</a></li>
                <li><a href="{{ url_for('public.about') }}">Om</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
</nav>

slasqrr/templates/rpi/rpi_layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">

    <title>{% block page_title %}

        SLASQRR

    {% endblock %}
    </title>
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <meta name="author" content="{% block meta_author %}{% endblock %}">

    <meta property="og:url" content="http://slasquen.rocks" />
    <meta property="og:title" content="Dödsfest är bra fest." />
    <meta property="og:site_name" content="Slasquen.rocks"/>
    <meta property="og:description" content="STABENs finfina eventsida för Slasquen. Kom igen det blir kul!"/>
    <meta property="og:image" content="http://slasquen.rocks/static/img/gruppbild.jpg" />

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width">

    {% assets "css_rpi" %}
        <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}

    {% block css %}{% endblock %}

</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}

{#    <header>{% block header %}{% endblock %}</header>#}
    <div class="{% block content_class %}container{% endblock content_class %}">

        <div role="main">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <div class="row">
                        <div class="col-md-12">
                            {% for category, message in messages %}
                                <div class="alert alert-{{ category }}">
                                    <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
                                    {{message}}
                                </div><!-- end .alert -->
                            {% endfor %}
                        </div><!-- end col-md -->
                    </div><!-- end row -->
                {% endif %}
            {% endwith %}

            {% block content %}{% endblock %}
        </div>

    </div><!-- end container -->

    <!-- JavaScript at the bottom for fast page loading -->
    {% assets "js_rpi" %}
        <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
    {% block js %}{% endblock %}
    {% if prod %}
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-62568300-1', 'auto');
            ga('send', 'pageview');
        </script>
    {% endif %}
    <!-- end scripts -->
{% endblock %}
</body>
</html>

slasqrr/templates/rpi/view.html
{% extends "rpi/rpi_layout.html" %}
{% block content %}

    <div class="row">
        <div class="col-xs-12">
            <h1 class="rocky text-center">Slasqrr</h1>
            <div id="pics" class="carousel slide" data-ride="carousel" data-intervall="5000" data-keyboard="false" data-pause="">

                <div id="items" class="carousel-inner">
                    <div class="item active">
                        <h1 id="first" class="rocky text-center">Slasqrr by STABEN</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <h1 class="text-center"><a href="{{ url_for("public.home") }}">www.slasquen.rocks</a></h1>
        </div>
    </div>

{% endblock %}

slasqrr/templates/users/members.html
{% extends "layout.html" %}
{% block content %}
    <h1>Welcome {{ session.username }}</h1>
    <h3>This is the members-only page.</h3>
{% endblock %}